In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from pandas import Series,DataFrame 
from datetime import date
import datetime as DT
import io
from scipy import stats
from sklearn.metrics import accuracy_score
import featuretools as ft

In [3]:
hello =("hello")
print(3*"hello")

hellohellohello

In [12]:
import re
s= "15553555254555555555555555555555555555555555555555555555555555555555555555555555555525333325555555555555555555555555555555555555235145555555555555555555555555555555555555555555555555555555555555555555555555554115555S55555555555555555555551455555555555555555555555555555255553555555555555555555555555555555555155555555555555555555555555555555555551555555555555555555555555555555555555555555555555555555555555555555555555555515555525525252525255555555555555555555555555555555555555555555555555555555555555555555555555552355555555555555555555555555555555555525545555555555555555555555555555555555535555555555555555555555555555555555555155555555525055555555555555555S5555512555255555555555555555555555555555555125555555555555555555555555555555552555555555555555435555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555435523555555555545555555555555555552555555155555555555555555555555555555555555555555555545555555555555355555555555555555555555555555555555555255555555555555555555555555555555555555215555555555555555555555555555255555555555555555555555555555555555533555155552555555555555555555555555555555555555555555555555555555555555555555555551211423235555555555555555555552334555555555555555555555555"
line = re.sub("[1-5]", "",s)
print(line)

S0S

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [81]:
train=pd.read_csv("C:/Users/Silent/Desktop/Data Science Projects/Running/Tunusia Financial Inclusion/Train_v2.csv")
test=pd.read_csv("C:/Users/Silent/Desktop/Data Science Projects/Running/Tunusia Financial Inclusion/Test_v2.csv")
samplesubmission = pd.read_csv("C:/Users/Silent/Desktop/Data Science Projects/Running/Tunusia Financial Inclusion/SubmissionFile.csv")
variabledef=pd.read_csv("C:/Users/Silent/Desktop/Data Science Projects/Running/Tunusia Financial Inclusion/VariableDefinitions.csv")

In [10]:
"""train=pd.read_csv("Train.csv")
test=pd.read_csv("Test.csv")
samplesubmission=pd.read_csv("SubmissionFile.csv")
variabledef=pd.read_csv("VariableDefinitions.csv")"""

'train=pd.read_csv("Train.csv")\ntest=pd.read_csv("Test.csv")\nsamplesubmission=pd.read_csv("SubmissionFile.csv")\nvariabledef=pd.read_csv("VariableDefinitions.csv")'

In [11]:
train.head()

,country,year,uniqueid,bank_account,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,education_level,job_type
0,Kenya,2018,uniqueid_1,Yes,Rural,Yes,3,24,Female,Spouse,Married/Living together,Secondary education,Self employed
1,Kenya,2018,uniqueid_2,No,Rural,No,5,70,Female,Head of Household,Widowed,No formal education,Government Dependent
2,Kenya,2018,uniqueid_3,Yes,Urban,Yes,5,26,Male,Other relative,Single/Never Married,Vocational/Specialised training,Self employed
3,Kenya,2018,uniqueid_4,No,Rural,Yes,5,34,Female,Head of Household,Married/Living together,Primary education,Formally employed Private
4,Kenya,2018,uniqueid_5,No,Urban,No,8,26,Male,Child,Single/Never Married,Primary education,Informally employed

In [12]:
#feature engineering begins
train["age_o_hs"]=train.age_of_respondent/train.household_size

test["age_o_hs"]=test.age_of_respondent/test.household_size

In [13]:
#feature engineering begins
train["age_m_hs"]=train.age_of_respondent-train.household_size
test["age_m_hs"]=test.age_of_respondent-test.household_size

In [14]:
train["log_age"]=train.age_of_respondent/10
test["log_age"]=test.age_of_respondent/10

In [15]:
#something1
train["loglog_age"]=train.age_of_respondent/100
test["loglog_age"]=test.age_of_respondent/100

In [16]:
#something2
train["buga"]=train.age_of_respondent-train.age_o_hs
test["buga"]=test.age_of_respondent-test.age_o_hs

In [17]:
#something3
train["bega"]=train.age_of_respondent-train.age_m_hs
test["bega"]=test.age_of_respondent-test.age_m_hs

In [18]:
#something3
train["fela"]=train.log_age-train.loglog_age
test["fela"]=test.log_age-test.loglog_age

In [19]:
#something3
train["riga"]=train.buga-train.fela
test["riga"]=test.buga-test.fela

In [20]:
#something3
train["ruga"]=train.log_age-train.household_size
test["ruga"]=test.log_age-test.household_size

In [21]:
#feature engineering begins
train["selah"]=train.age_of_respondent-train.log_age
test["selah"]=test.age_of_respondent-test.log_age

In [22]:
#something3
train["year_log"]=train.year/10
test["year_log"]=test.year/10

In [23]:
#something3
train["year_loglog"]=train.year/100
test["year_loglog"]=test.year/100

In [24]:
#feature engineering begins
train["blah"]=train.year-train.age_of_respondent
test["blah"]=test.year-test.age_of_respondent

In [25]:
#something3
train["yeardiv"]=train.year/train.age_of_respondent
test["yeardiv"]=test.year/test.age_of_respondent

In [26]:
#something3
train["yeardivee"]=train.year/train.household_size
test["yeardivee"]=test.year/test.household_size

In [27]:
#Creating and storing our target variable in a seperate dataframe
bankaccount=DataFrame(train["bank_account"])

# ENCODING CATEGORICAL DATA USING DUMMY VARIABLES

# Encoding the INDEPENDENT Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
bankaccount.bank_account = labelencoder_X.fit_transform(bankaccount.bank_account)

In [28]:
#updating bank account column
train.bank_account=bankaccount.bank_account

In [29]:
#A more closer look
corr=train.corr()
corr.style.background_gradient(cmap='coolwarm')

In [30]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23524 entries, 0 to 23523
Data columns (total 28 columns):
country                   23524 non-null object
year                      23524 non-null int64
uniqueid                  23524 non-null object
bank_account              23524 non-null int32
location_type             23524 non-null object
cellphone_access          23524 non-null object
household_size            23524 non-null int64
age_of_respondent         23524 non-null int64
gender_of_respondent      23524 non-null object
relationship_with_head    23524 non-null object
marital_status            23524 non-null object
education_level           23524 non-null object
job_type                  23524 non-null object
age_o_hs                  23524 non-null float64
age_m_hs                  23524 non-null int64
log_age                   23524 non-null float64
loglog_age                23524 non-null float64
buga                      23524 non-null float64
bega                      23524 non-null int64
fela                      23524 non-null float64
riga                      23524 non-null float64
ruga                      23524 non-null float64
selah                     23524 non-null float64
year_log                  23524 non-null float64
year_loglog               23524 non-null float64
blah                      23524 non-null int64
yeardiv                   23524 non-null float64
yeardivee                 23524 non-null float64
dtypes: float64(12), int32(1), int64(6), object(9)
memory usage: 4.9+ MB

In [31]:
train.shape

(23524, 28)

In [32]:
test.shape

(10086, 27)

In [33]:
#Here we want to merge our training and test set but for the columns to be same, we must first take of our target in train
train=train.drop(['bank_account'], axis=1)

In [34]:
#Now we merge BUT first we must create 2 train columns in our test and train set in order to id and seperate them later
train['train']=1
test['train']=0

In [35]:
#we join the test and train sets together for uniform cleaning
combined=pd.concat([train, test])


"""One very important to note over here is that we haven’t specified the axis while concatenating which means we are combining along the rows.So what this will do is combine the test set below the train set with the ‘train’ column acting as the demarkation(all rows with 1 belong to train set and those with 0 to the test part).

Now do the encoding you require on the required column and save it in a new dataset."""

'One very important to note over here is that we haven’t specified the axis while concatenating which means we are combining along the rows.So what this will do is combine the test set below the train set with the ‘train’ column acting as the demarkation(all rows with 1 belong to train set and those with 0 to the test part).\n\nNow do the encoding you require on the required column and save it in a new dataset.'

In [36]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33610 entries, 0 to 10085
Data columns (total 28 columns):
country                   33610 non-null object
year                      33610 non-null int64
uniqueid                  33610 non-null object
location_type             33610 non-null object
cellphone_access          33610 non-null object
household_size            33610 non-null int64
age_of_respondent         33610 non-null int64
gender_of_respondent      33610 non-null object
relationship_with_head    33610 non-null object
marital_status            33610 non-null object
education_level           33610 non-null object
job_type                  33610 non-null object
age_o_hs                  33610 non-null float64
age_m_hs                  33610 non-null int64
log_age                   33610 non-null float64
loglog_age                33610 non-null float64
buga                      33610 non-null float64
bega                      33610 non-null int64
fela                      33610 non-null float64
riga                      33610 non-null float64
ruga                      33610 non-null float64
selah                     33610 non-null float64
year_log                  33610 non-null float64
year_loglog               33610 non-null float64
blah                      33610 non-null int64
yeardiv                   33610 non-null float64
yeardivee                 33610 non-null float64
train                     33610 non-null int64
dtypes: float64(12), int64(7), object(9)
memory usage: 7.4+ MB

In [37]:
# making copy of team column 
new = combined["country"].copy()

In [38]:
combined["uniqueid"]= combined["uniqueid"].str.cat(new, sep =" x ")

In [39]:
combined.head()

,country,year,uniqueid,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,...,fela,riga,ruga,selah,year_log,year_loglog,blah,yeardiv,yeardivee,train
0,Kenya,2018,uniqueid_1 x Kenya,Rural,Yes,3,24,Female,Spouse,Married/Living together,...,2.16,13.84,-0.6,21.6,201.8,20.18,1994,84.083333,672.666667,1
1,Kenya,2018,uniqueid_2 x Kenya,Rural,No,5,70,Female,Head of Household,Widowed,...,6.30,49.70,2.0,63.0,201.8,20.18,1948,28.828571,403.600000,1
2,Kenya,2018,uniqueid_3 x Kenya,Urban,Yes,5,26,Male,Other relative,Single/Never Married,...,2.34,18.46,-2.4,23.4,201.8,20.18,1992,77.615385,403.600000,1
3,Kenya,2018,uniqueid_4 x Kenya,Rural,Yes,5,34,Female,Head of Household,Married/Living together,...,3.06,24.14,-1.6,30.6,201.8,20.18,1984,59.352941,403.600000,1
4,Kenya,2018,uniqueid_5 x Kenya,Urban,No,8,26,Male,Child,Single/Never Married,...,2.34,20.41,-5.4,23.4,201.8,20.18,1992,77.615385,252.250000,1

In [40]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33610 entries, 0 to 10085
Data columns (total 28 columns):
country                   33610 non-null object
year                      33610 non-null int64
uniqueid                  33610 non-null object
location_type             33610 non-null object
cellphone_access          33610 non-null object
household_size            33610 non-null int64
age_of_respondent         33610 non-null int64
gender_of_respondent      33610 non-null object
relationship_with_head    33610 non-null object
marital_status            33610 non-null object
education_level           33610 non-null object
job_type                  33610 non-null object
age_o_hs                  33610 non-null float64
age_m_hs                  33610 non-null int64
log_age                   33610 non-null float64
loglog_age                33610 non-null float64
buga                      33610 non-null float64
bega                      33610 non-null int64
fela                      33610 non-null float64
riga                      33610 non-null float64
ruga                      33610 non-null float64
selah                     33610 non-null float64
year_log                  33610 non-null float64
year_loglog               33610 non-null float64
blah                      33610 non-null int64
yeardiv                   33610 non-null float64
yeardivee                 33610 non-null float64
train                     33610 non-null int64
dtypes: float64(12), int64(7), object(9)
memory usage: 7.4+ MB

In [41]:
import featuretools as ft

In [42]:
ft.primitives.list_primitives()

,name,type,description
0,time_since_last,aggregation,Calculates the time elapsed since the last dat...
1,min,aggregation,"Calculates the smallest value, ignoring `NaN` ..."
2,all,aggregation,Calculates if all values are 'True' in a list.
3,num_unique,aggregation,"Determines the number of distinct values, igno..."
4,any,aggregation,Determines if any value is 'True' in a list.
5,skew,aggregation,Computes the extent to which a distribution di...
6,trend,aggregation,Calculates the trend of a variable over time.
7,mode,aggregation,Determines the most commonly repeated value.
8,max,aggregation,"Calculates the highest value, ignoring `NaN` v..."
9,n_most_common,aggregation,Determines the `n` most common elements.
10,std,aggregation,Computes the dispersion relative to the mean v...
11,num_true,aggregation,Counts the number of `True` values.
12,mean,aggregation,Computes the average for a list of values.
13,sum,aggregation,"Calculates the total addition, ignoring `NaN`."
14,count,aggregation,"Determines the total number of values, excludi..."
15,last,aggregation,Determines the last value in a list.
16,avg_time_between,aggregation,Computes the average number of seconds between...
17,percent_true,aggregation,Determines the percent of `True` values.
18,time_since_first,aggregation,Calculates the time elapsed since the first da...
19,median,aggregation,Determines the middlemost number in a list of ...
20,num_words,transform,Determines the number of words in a string by ...
21,modulo_by_feature,transform,Return the modulo of a scalar by each element ...
22,cum_min,transform,Calculates the cumulative minimum.
23,not_equal,transform,Determines if values in one list are not equal...
24,is_weekend,transform,Determines if a date falls on a weekend.
25,equal,transform,Determines if values in one list are equal to ...
26,multiply_numeric_scalar,transform,Multiply each element in the list by a scalar.
27,greater_than,transform,Determines if values in one list are greater t...
28,isin,transform,Determines whether a value is present in a pro...
29,weekday,transform,Determines the day of the week from a datetime.
...,...,...,...
45,negate,transform,Negates a numeric value.
46,or,transform,Element-wise logical OR of two lists.
47,scalar_subtract_numeric_feature,transform,Subtract each value in the list from a given s...
48,less_than_equal_to,transform,Determines if values in one list are less than...
49,num_characters,transform,Calculates the number of characters in a string.
50,longitude,transform,Returns the second tuple value in a list of La...
51,time_since,transform,Calculates time from a value to a specified cu...
52,add_numeric,transform,Element-wise addition of two lists.
53,divide_numeric,transform,Element-wise division of two lists.
54,percentile,transform,Determines the percentile rank for each value ...
55,week,transform,Determines the week of the year from a datetime.
56,second,transform,Determines the seconds value of a datetime.
57,not_equal_scalar,transform,Determines if values in a list are not equal t...
58,cum_mean,transform,Calculates the cumulative mean.
59,latitude,transform,Returns the first tuple value in a list of Lat...
60,diff,transform,Compute the difference between the value in a ...
61,and,transform,Element-wise logical AND of two lists.
62,month,transform,Determines the month value of a datetime.
63,greater_than_equal_to_scalar,transform,Determines if values are greater than or equal...
64,year,transform,Determines the year value of a datetime.
65,minute,transform,Determines the minutes value of a datetime.
66,add_numeric_scalar,transform,Add a scalar to each value in the list.
67,greater_than_scalar,transform,Determines if values are greater than a given ...
68,less_than_equal_to_scalar,transform,Determines if values are less than or equal to...
69,divide_numeric_scalar,transform,Divide each element in the list by a scalar.
70,equal_scalar,transform,Determines if values in a list are equal to a ...
71,hour,transform,Determines the hour value of a datetime.
72,less_than_scalar,transform,Determines if values are less than a given sca...
73,multiply_numeric,transform,Element-wise multiplication of two lists.
74,divide_by_feature,transform,Divide a scalar by each value in the list.

In [43]:
#categorizing categorical variables

#ENCODINGS GET DUMMIES STARTS HERE


#NOW WE ENCODE

combined1=pd.get_dummies(combined['country'], drop_first=True)

#now we encode

combined2=pd.get_dummies(combined['year'], drop_first=True)

#now we encode

combined3=pd.get_dummies(combined['location_type'], drop_first=True)

combined4=pd.get_dummies(combined['cellphone_access'], drop_first=True)

#now we encode

combined5=pd.get_dummies(combined['gender_of_respondent'], drop_first=True)

#now we encode

combined6=pd.get_dummies(combined['relationship_with_head'], drop_first=True)


combined7=pd.get_dummies(combined['marital_status'], drop_first=True)

#now we encode

combined8=pd.get_dummies(combined['education_level'], drop_first=True)

#now we encode

combined9=pd.get_dummies(combined['job_type'], drop_first=True)

In [44]:
#Now we drop the weblog_date column since we have processed it
combined=combined.drop(['country'], axis=1)
combined=combined.drop(['year'], axis=1)

combined=combined.drop(['location_type'], axis=1)
combined=combined.drop(['cellphone_access'], axis=1)
#Now we drop the weblog_date column since we have processed it
combined=combined.drop(['gender_of_respondent'], axis=1)
combined=combined.drop(['relationship_with_head'], axis=1)

combined=combined.drop(['marital_status'], axis=1)
combined=combined.drop(['education_level'], axis=1)
combined=combined.drop(['job_type'], axis=1)

In [45]:
#now we combine all datasets together
combined=pd.concat([combined,combined1,combined2,combined3,combined4,combined5,combined6,combined7,combined8,combined9], axis=1)

In [46]:
#Now its time to separate those two datasets and we are done with both the train and test set now 
#containing the same number of columns.
train_df=combined[combined['train']==1]
test_df=combined[combined['train']==0]
#we now drop the train columns we created in test and train set
train_df.drop(['train'], axis=1, inplace=True)
test_df.drop(['train'], axis=1, inplace=True)

In [47]:
#converting test_df to csv in other to get its reformatted unique id
#test_set = pd.DataFrame(test_df, columns=['uniqueid']).to_csv('test_setnew.csv')

In [48]:
#dropping uniqueid in test_df
test_df=test_df.drop(['uniqueid'], axis=1)
train_df=train_df.drop(['uniqueid'], axis=1)

In [49]:
test_df.head()

,household_size,age_of_respondent,age_o_hs,age_m_hs,log_age,loglog_age,buga,bega,fela,riga,...,Vocational/Specialised training,Farming and Fishing,Formally employed Government,Formally employed Private,Government Dependent,Informally employed,No Income,Other Income,Remittance Dependent,Self employed
0,3,30,10.000000,27,3.0,0.30,20.000000,3,2.70,17.300000,...,0,0,1,0,0,0,0,0,0,0
1,7,51,7.285714,44,5.1,0.51,43.714286,7,4.59,39.124286,...,1,0,0,1,0,0,0,0,0,0
2,3,77,25.666667,74,7.7,0.77,51.333333,3,6.93,44.403333,...,0,0,0,0,0,0,0,0,1,0
3,6,39,6.500000,33,3.9,0.39,32.500000,6,3.51,28.990000,...,0,0,0,0,0,0,0,0,1,0
4,3,16,5.333333,13,1.6,0.16,10.666667,3,1.44,9.226667,...,0,0,0,0,0,0,0,0,1,0

In [50]:
train_df.head()

,household_size,age_of_respondent,age_o_hs,age_m_hs,log_age,loglog_age,buga,bega,fela,riga,...,Vocational/Specialised training,Farming and Fishing,Formally employed Government,Formally employed Private,Government Dependent,Informally employed,No Income,Other Income,Remittance Dependent,Self employed
0,3,24,8.00,21,2.4,0.24,16.00,3,2.16,13.84,...,0,0,0,0,0,0,0,0,0,1
1,5,70,14.00,65,7.0,0.70,56.00,5,6.30,49.70,...,0,0,0,0,1,0,0,0,0,0
2,5,26,5.20,21,2.6,0.26,20.80,5,2.34,18.46,...,1,0,0,0,0,0,0,0,0,1
3,5,34,6.80,29,3.4,0.34,27.20,5,3.06,24.14,...,0,0,0,1,0,0,0,0,0,0
4,8,26,3.25,18,2.6,0.26,22.75,8,2.34,20.41,...,0,0,0,0,0,1,0,0,0,0

In [51]:
#now we combine back our target to our train set together
train_df=pd.concat([train_df,bankaccount], axis=1)

In [1]:
train_df.head(20)

NameError: name 'train_df' is not defined

In [53]:
train_df.shape

(23524, 49)

In [54]:
# #Splitting  the dataset into X and y
# X = train_df.iloc[:, 0:391].values
# y = train_df.iloc[:, -1].values
X  = train_df.drop('bank_account',axis = 1)
y = train_df['bank_account']

In [55]:
# Splitting the dataset into the Training set and validation set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40, random_state =0)

In [56]:
#CAtboost: training the model so that it have to detect overfitting and select best parameters. To do that you need to have a validation dataset.
from sklearn.model_selection import train_test_split

X_train, X_validation, y_train, y_validation = train_test_split(X, y, train_size=0.75, random_state=42)

In [57]:
#catboost
from catboost import CatBoostClassifier
model = CatBoostClassifier(
    iterations=5,
    random_seed=0,
    learning_rate=0.1
)
model.fit(
    X_train, y_train,
    #cat_features=cat_features,
    eval_set=(X_validation, y_validation),
    logging_level='Silent'
)
print('Model is fitted: ' + str(model.is_fitted()))
print('Model params:')
print(model.get_params())

Model is fitted: True
Model params:
{'iterations': 5, 'learning_rate': 0.1, 'random_seed': 0}

In [58]:
# Random Forests
from sklearn.ensemble import RandomForestClassifier
random_forest = RandomForestClassifier(n_estimators=100)
#random_forest = RandomForestClassifier(n_estimators=100, criterion='entropy', max_depth=10, max_features='sqrt', min_samples_split=5)

random_forest.fit(X_train, y_train)

y_pred_1 = random_forest.predict(X_test)

random_forest.score(X_train, y_train)

0.9813523777135408

In [63]:
da = pd.read_csv('C:/Users/Silent/Desktop/Data Science Projects/Running/Tunusia Financial Inclusion/xgb.csv')

In [65]:
da.bank_account.value_counts()

0    9458
1     628
Name: bank_account, dtype: int64

In [73]:
test

,country,year,uniqueid,location_type,cellphone_access,household_size,age_of_respondent,gender_of_respondent,relationship_with_head,marital_status,...,fela,riga,ruga,selah,year_log,year_loglog,blah,yeardiv,yeardivee,train
0,Kenya,2018,uniqueid_6056,Urban,Yes,3,30,Male,Head of Household,Married/Living together,...,2.70,17.300000,0.0,27.0,201.8,20.18,1988,67.266667,672.666667,0
1,Kenya,2018,uniqueid_6060,Urban,Yes,7,51,Male,Head of Household,Married/Living together,...,4.59,39.124286,-1.9,45.9,201.8,20.18,1967,39.568627,288.285714,0
2,Kenya,2018,uniqueid_6065,Rural,No,3,77,Female,Parent,Married/Living together,...,6.93,44.403333,4.7,69.3,201.8,20.18,1941,26.207792,672.666667,0
3,Kenya,2018,uniqueid_6072,Rural,No,6,39,Female,Head of Household,Married/Living together,...,3.51,28.990000,-2.1,35.1,201.8,20.18,1979,51.743590,336.333333,0
4,Kenya,2018,uniqueid_6073,Urban,No,3,16,Male,Child,Single/Never Married,...,1.44,9.226667,-1.4,14.4,201.8,20.18,2002,126.125000,672.666667,0
5,Kenya,2018,uniqueid_6074,Rural,Yes,4,25,Female,Spouse,Married/Living together,...,2.25,16.500000,-1.5,22.5,201.8,20.18,1993,80.720000,504.500000,0
6,Kenya,2018,uniqueid_6075,Rural,Yes,4,32,Female,Head of Household,Divorced/Seperated,...,2.88,21.120000,-0.8,28.8,201.8,20.18,1986,63.062500,504.500000,0
7,Kenya,2018,uniqueid_6076,Urban,Yes,3,24,Female,Spouse,Married/Living together,...,2.16,13.840000,-0.6,21.6,201.8,20.18,1994,84.083333,672.666667,0
8,Kenya,2018,uniqueid_6077,Rural,Yes,4,22,Female,Child,Single/Never Married,...,1.98,14.520000,-1.8,19.8,201.8,20.18,1996,91.727273,504.500000,0
9,Kenya,2018,uniqueid_6078,Urban,Yes,1,42,Male,Head of Household,Divorced/Seperated,...,3.78,-3.780000,3.2,37.8,201.8,20.18,1976,48.047619,2018.000000,0
10,Kenya,2018,uniqueid_6079,Rural,No,5,18,Male,Child,Single/Never Married,...,1.62,12.780000,-3.2,16.2,201.8,20.18,2000,112.111111,403.600000,0
11,Kenya,2018,uniqueid_6080,Rural,No,3,20,Male,Other relative,Married/Living together,...,1.80,11.533333,-1.0,18.0,201.8,20.18,1998,100.900000,672.666667,0
12,Kenya,2018,uniqueid_6081,Rural,No,7,32,Female,Spouse,Married/Living together,...,2.88,24.548571,-3.8,28.8,201.8,20.18,1986,63.062500,288.285714,0
13,Kenya,2018,uniqueid_6082,Urban,Yes,6,19,Female,Child,Married/Living together,...,1.71,14.123333,-4.1,17.1,201.8,20.18,1999,106.210526,336.333333,0
14,Kenya,2018,uniqueid_6083,Urban,Yes,2,26,Female,Child,Single/Never Married,...,2.34,10.660000,0.6,23.4,201.8,20.18,1992,77.615385,1009.000000,0
15,Kenya,2018,uniqueid_6084,Rural,Yes,4,18,Male,Child,Single/Never Married,...,1.62,11.880000,-2.2,16.2,201.8,20.18,2000,112.111111,504.500000,0
16,Kenya,2018,uniqueid_6085,Rural,Yes,5,35,Male,Head of Household,Married/Living together,...,3.15,24.850000,-1.5,31.5,201.8,20.18,1983,57.657143,403.600000,0
17,Kenya,2018,uniqueid_6086,Rural,No,1,68,Female,Head of Household,Divorced/Seperated,...,6.12,-6.120000,5.8,61.2,201.8,20.18,1950,29.676471,2018.000000,0
18,Kenya,2018,uniqueid_6087,Urban,No,5,20,Female,Child,Single/Never Married,...,1.80,14.200000,-3.0,18.0,201.8,20.18,1998,100.900000,403.600000,0
19,Kenya,2018,uniqueid_6088,Urban,No,7,70,Male,Head of Household,Married/Living together,...,6.30,53.700000,0.0,63.0,201.8,20.18,1948,28.828571,288.285714,0
20,Kenya,2018,uniqueid_6089,Rural,Yes,4,34,Female,Spouse,Married/Living together,...,3.06,22.440000,-0.6,30.6,201.8,20.18,1984,59.352941,504.500000,0
21,Kenya,2018,uniqueid_6090,Rural,No,1,95,Female,Head of Household,Widowed,...,8.55,-8.550000,8.5,85.5,201.8,20.18,1923,21.242105,2018.000000,0
22,Kenya,2018,uniqueid_6091,Rural,Yes,1,30,Female,Head of Household,Single/Never Married,...,2.70,-2.700000,2.0,27.0,201.8,20.18,1988,67.266667,2018.000000,0
23,Kenya,2018,uniqueid_6092,Urban,Yes,4,27,Male,Head of Household,Married/Living together,...,2.43,17.820000,-1.3,24.3,201.8,20.18,1991,74.740741,504.500000,0
24,Kenya,2018,uniqueid_6093,Rural,Yes,1,70,Female,Head of Household,Widowed,...,6.30,-6.300000,6.0,63.0,201.8,20.18,1948,28.828571,2018.000000,0
25,Kenya,2018,uniqueid_6094,Urban,No,9,21,Female,Child,Single/Never Married,...,1.89,16.776667,-6.9,18.9,201.8,20.18,1997,96.095238,224.222222,0
26,Kenya,2018,uniqueid_6095,Rural,No,4,45,Male,Head of Household,Married/Living together,...,4.05,29.700000,0.5,40.5,201.8,20.18,1973,44.844444,504.500000,0
27,Kenya,2018,uniqueid_6096,Rural,Yes,6,52,Female,Head of Household,Single/Never Married,...,4.68,38.653333,-0.8,46.8,201.8,20.18,1966,38.807692,336.333333,0
28,Kenya,2018,uniqueid_6097,Rural,Yes,1,44,Female,Head of Household,Divorced/Seperated,...,3.96,-3.960000,3.4,39.6,201.8,20.18,1974,45.863636,2018.000000,0
29,Kenya,2018,uniqueid_6098,Urban,Yes,4,21,Female,Child,Single/Never Married,...,1.89,13.860000,-1.9,18.9,201.8,20.18,1997,96.095238,504.500000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10056,Uganda,2018,uniqueid_2973,Urban,Yes,7,31,Female,Spouse,Married/Living together,...,2.79,23.781429,-3.9,27.9,201.8,20.18,1987,65.096774,288.285714,0
10057,Uganda,2018,uniqueid_2974,Rural,Yes,10,18,Male,Child,Single/Never Married,...,1.62,14.580000,-8.2,16.2,201.8,20.18,2000,112.111111,201.800000,0
10058,Uganda,2018,uniqueid_2975,Rural,Yes,7,42,Male,Head of Household,Married/Living together,...,3.78,32.220000,-2.8,37.8,201.8,20.18,1976,48.047619,288.285714,0
10059,Uganda,2018,uniqueid_2976,Rural,No,6,50,Male,Head of Household,Married/Living together,...,4.50,37.166667,-1.0,45.0,201.8,20.18,1968,40.360000,336.333333,0
10060,Uganda,2018,uniqueid_2977,Urban,Yes,8,19,Female,Parent,Single/Never Married,...,1.71,14.915000,-6.1,17.1,201.8,20.18,1999,106.210526,252.250000,0
10061,Uganda,2018,uniqueid_2978,Urban,No,2,49,Female,Head of Household,Widowed,...,4.41,20.090000,2.9,44.1,201.8,20.18,1969,41.183673,1009.000000,0
10062,Uganda,2018,uniqueid_2979,Rural,Yes,2,32,Male,Head of Household,Married/Living together,...,2.88,13.120000,1.2,28.8,201.8,20.18,1986,63.062500,1009.000000,0
10063,Uganda,2018,uniqueid_2980,Rural,No,4,47,Female,Head of Household,Married/Living together,...,4.23,31.020000,0.7,42.3,201.8,20.18,1971,42.936170,504.500000,0
10064,Uganda,2018,uniqueid_2981,Rural,No,7,40,Female,Head of Household,Married/Living together,...,3.60,30.685714,-3.0,36.0,201.8,20.18,1978,50.450000,288.285714,0
10065,Uganda,2018,uniqueid_2982,Urban,Yes,2,23,Male,Head of Household,Single/Never Married,...,2.07,9.430000,0.3,20.7,201.8,20.18,1995,87.739130,1009.000000,0
10066,Uganda,2018,uniqueid_2983,Rural,Yes,7,32,Female,Spouse,Married/Living together,...,2.88,24.548571,-3.8,28.8,201.8,20.18,1986,63.062500,288.285714,0
10067,Uganda,2018,uniqueid_2984,Urban,Yes,10,32,Female,Spouse,Married/Living together,...,2.88,25.920000,-6.8,28.8,201.8,20.18,1986,63.062500,201.800000,0
10068,Uganda,2018,uniqueid_2985,Rural,No,12,20,Male,Head of Household,Married/Living together,...,1.80,16.533333,-10.0,18.0,201.8,20.18,1998,100.900000,168.166667,0
10069,Uganda,2018,uniqueid_2986,Rural,Yes,7,37,Female,Spouse,Married/Living together,...,3.33,28.384286,-3.3,33.3,201.8,20.18,1981,54.540541,288.285714,0
10070,Uganda,2018,uniqueid_2987,Urban,Yes,5,18,Female,Parent,Single/Never Married,...,1.62,12.780000,-3.2,16.2,201.8,20.18,2000,112.111111,403.600000,0
10071,Uganda,2018,uniqueid_2988,Rural,Yes,3,38,Female,Head of Household,Married/Living together,...,3.42,21.913333,0.8,34.2,201.8,20.18,1980,53.105263,672.666667,0
10072,Uganda,2018,uniqueid_2989,Rural,No,2,65,Female,Head of Household,Married/Living together,...,5.85,26.650000,4.5,58.5,201.8,20.18,1953,31.046154,1009.000000,0
10073,Uganda,2018,uniqueid_2990,Rural,Yes,3,59,Female,Head of Household,Widowed,...,5.31,34.023333,2.9,53.1,201.8,20.18,1959,34.203390,672.666667,0
10074,Uganda,2018,uniqueid_2991,Rural,Yes,2,34,Female,Spouse,Married/Living together,...,3.06,13.940000,1.4,30.6,201.8,20.18,1984,59.352941,1009.000000,0
10075,Uganda,2018,uniqueid_2992,Rural,No,4,27,Female,Spouse,Married/Living together,...,2.43,17.820000,-1.3,24.3,201.8,20.18,1991,74.740741,504.500000,0
10076,Uganda,2018,uniqueid_2993,Rural,Yes,5,46,Male,Head of Household,Married/Living together,...,4.14,32.660000,-0.4,41.4,201.8,20.18,1972,43.869565,403.600000,0
10077,Uganda,2018,uniqueid_2994,Rural,Yes,6,30,Female,Spouse,Married/Living together,...,2.70,22.300000,-3.0,27.0,201.8,20.18,1988,67.266667,336.333333,0
10078,Uganda,2018,uniqueid_2995,Rural,No,8,30,Female,Spouse,Married/Living together,...,2.70,23.550000,-5.0,27.0,201.8,20.18,1988,67.266667,252.250000,0
10079,Uganda,2018,uniqueid_2996,Urban,Yes,9,37,Female,Spouse,Married/Living together,...,3.33,29.558889,-5.3,33.3,201.8,20.18,1981,54.540541,224.222222,0
10080,Uganda,2018,uniqueid_2997,Rural,Yes,2,22,Male,Other non-relatives,Single/Never Married,...,1.98,9.020000,0.2,19.8,201.8,20.18,1996,91.727273,1009.000000,0
10081,Uganda,2018,uniqueid_2998,Rural,No,2,62,Female,Spouse,Married/Living together,...,5.58,25.420000,4.2,55.8,201.8,20.18,1956,32.548387,1009.000000,0
10082,Uganda,2018,uniqueid_2999,Urban,Yes,8,42,Male,Head of Household,Married/Living together,...,3.78,32.970000,-3.8,37.8,201.8,20.18,1976,48.047619,252.250000,0
10083,Uganda,2018,uniqueid_3000,Urban,Yes,1,39,Male,Head of Household,Single/Never Married,...,3.51,-3.510000,2.9,35.1,201.8,20.18,1979,51.743590,2018.000000,0
10084,Uganda,2018,uniqueid_3001,Rural,Yes,6,28,Female,Spouse,Married/Living together,...,2.52,20.813333,-3.2,25.2,201.8,20.18,1990,72.071429,336.333333,0
10085,Uganda,2018,uniqueid_3002,Urban,Yes,7,16,Male,Other relative,Single/Never Married,...,1.44,12.274286,-5.4,14.4,201.8,20.18,2002,126.125000,288.285714,0

In [78]:
samplesubmission = pd.read_csv("C:/Users/Silent/Desktop/Data Science Projects/Running/Tunusia Financial Inclusion/xgb.csv")

In [67]:
da.to_csv('C:/Users/Silent/Desktop/Data Science Projects/Running/Tunusia Financial Inclusion/new.csv',index = False)

In [82]:
submission = pd.DataFrame(index=test.index,columns=['uniqueid','bank_account'])

submission['uniqueid'] = test['uniqueid']

submission['bank_account'] = random_forest.predict(X_test)

# create submit_file

submission.to_csv('C:/Users/Silent/Desktop/Data Science Projects/Running/Tunusia Financial Inclusion/any.csv',index=False)

ValueError: Length of values does not match length of index

In [84]:
submission = pd.DataFrame(index=test.index,columns=['uniqueid','bank_account'])
submission['uniqueid'] = test['uniqueid']
submission.bank_account=0
submission.to_csv('C:/Users/Silent/Desktop/Data Science Projects/Running/Tunusia Financial Inclusion/new1.csv',index=False)

In [ ]:
# Function to remove duplicates in a sorted array 
def removeDupsSorted(List): 
    res_ind = 1
    ip_ind = 1
  
    # In place removal of duplicate characters 
    while ip_ind != len(List): 
        if List[ip_ind] != List[ip_ind-1]: 
            List[res_ind] = List[ip_ind] 
            res_ind += 1
        ip_ind+=1
  
    # After above step string is efgkorskkorss. 
    # Removing extra kkorss after string 
    string = toString(List[0:res_ind]) 
  
    return string 
  
# Function removes duplicate characters from the string 
# This function work in-place and fills null characters 
# in the extra space left 
def removeDups(string): 
    # Convert string to list 
    List = toMutable(string) 
  
    # Sort the character list 
    List.sort() 
  
    # Remove duplicates from sorted 
    return removeDupsSorted(List)

In [58]:
#We now build our model  LOGISTIC REGRESSION
#checking accuracy
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

C:\Users\Silent\Anaconda3\Conda\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [63]:
## Predicting the Test set results
y_pred = classifier.predict(X_test)
import sklearn
sklearn.metrics.accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)

0.8859723698193411

In [5]:
# Fitting XGBoost to the Training set
from xgboost import XGBClassifier
classifier = XGBClassifier(n_estimators=200)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)
#metrics
import sklearn
sklearn.metrics.accuracy_score(y_test, y_pred, normalize=True, sample_weight=None)

NameError: name 'X_train' is not defined

In [59]:
X_train.columns == test_df.columns

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [60]:
# Predicting the Test set results and converting to csv
pred_fir = classifier.predict(test_df)
prediction = pd.DataFrame(pred_fir, columns=['bank_account'])

XGBoostError: need to call fit or load_model beforehand

In [1]:
 from catboost import CatBoostClassifier
 params = {'depth':[3,1,2,6,4,5,7,8,9,10],
           'iterations':[250,100,500,1000],
           'learning_rate':[0.03,0.001,0.01,0.1,0.2,0.3], 
           'l2_leaf_reg':[3,1,5,10,100],
           'border_count':[32,5,10,20,50,100,200],
           'ctr_border_count':[50,5,10,20,100,200],
           'thread_count':4}

In [4]:
from xgboost import XGBClassifier

In [61]:
da.bank_account.value_counts()

NameError: name 'da' is not defined

In [61]:
da.to_csv('gp.csv',index = False)

NameError: name 'da' is not defined

In [1]:
submission_df = pd.DataFrame({"uniqueid": test["uniqueid"] + " x " + test["country"],

"bank_account": test.target

})

NameError: name 'pd' is not defined